# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=200)),
                ('Autor', models.CharField(max_length=200)),
                ('Editorial', models.CharField(max_length=200)),
                ('ISBN', models.CharField(max_length=200)),
                ('Precio', models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True)),
            ],
        ),
    ]
